
name: Create Plugin

on: 
  issues: 
    types: 
      - opened
      - reopened

jobs:
  createplugin:
    name: Create Plugin
    runs-on: ubuntu-latest
    concurrency:
      group: push-branch-${{ github.ref }}
      cancel-in-progress: false
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - name: Create paths
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PLUGIN_REPOSITORY="${{ github.event.issue.body }}" python3 .github/workflows/get-repository.py
      - name: Get requested repository
        uses: andstor/file-reader-action@v1
        with:
          path: 'repository'
        id: repository
      - name: Get requested repository name
        uses: andstor/file-reader-action@v1
        with:
          path: 'repository_name'
        id: repository_name
      - name: Get data path
        uses: andstor/file-reader-action@v1
        with:
          path: 'datapath'
        id: datapath
      - name: Get multipluginname
        uses: andstor/file-reader-action@v1
        with:
          path: 'multipluginname'
        id: multipluginname
      - name: Create downloaded directory
        run: mkdir ${{ steps.repository_name.outputs.contents }}
      - name: Download requested repository
        uses: actions/checkout@v6
        with:
          repository: ${{ steps.repository.outputs.contents }}
          path: ${{ steps.repository_name.outputs.contents }}
      - name: Remove unneeded files
        run: |
          mv ${{ steps.datapath.outputs.contents }} ${{ steps.repository_name.outputs.contents }}/..
          ls
          rm -r ${{ steps.repository_name.outputs.contents }}
          mv data ${{ steps.multipluginname.outputs.contents }}
          pwd
          ls ${{ steps.multipluginname.outputs.contents }}
      - name: Generate plugin
        run: |
          REPOSITORY="${{ steps.multipluginname.outputs.contents }}" python3 .github/workflows/generate.py
      - name: Create plugin.txt
        run: |
          PLUGIN="${{ steps.multipluginname.outputs.contents }}" python3 .github/workflows/create-plugin-txt.py
      - name: Move files into subfolder and list contents
        run: |
          PLUGIN_NAME=${{ steps.multipluginname.outputs.contents }}-ship.merging-compat
          mkdir -p $PLUGIN_NAME/data
          mv plugin.txt $PLUGIN_NAME
          mv ship_upgrades_mission.txt $PLUGIN_NAME/data
          mv ship_upgrades_ships.txt $PLUGIN_NAME/data
          mv assets/icon.png $PLUGIN_NAME/
          mv assets/icon@2x.png $PLUGIN_NAME/
      - name: Zip plugin
        run: |
          PLUGIN="${{ steps.multipluginname.outputs.contents }}"
          echo "Zipping file: '$PLUGIN'"
          zip -r "$PLUGIN-compatibility.zip" "$PLUGIN-ship.merging-compat"
      - name: Upload plugin
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Add Comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            The compatibility plugin between ship.merging and ${{ steps.multipluginname.outputs.contents }} was generated, so this issue is being automatically closed.
            You can download it on the [release page](https://github.com/TheGiraffe3/generate-ship-merging-compatibility/releases/tag/latest) as ${{ steps.repository_name.outputs.contents }}-compatibility.zip.
      - if: contains(github.event.issue.labels.*.name, 'autoclose')
        name: Close Issue
        uses: peter-evans/close-issue@v3
